"""建立工作日曆的三張表

calendar_official_days（官方辦公日曆的特殊日）、calendar_official_years（完整涵蓋的年份與匯入時間）、
calendar_overrides（管理員的例外日）。都不軟刪。autogenerate 產生，逐行看過、沒有手改
（calendar_year 的 autoincrement=False 要保留：SMALLINT 主鍵預設會變成 SMALLSERIAL）。

Revision ID: a2eddfa35bec
Revises: 5c2126ce0487
Create Date: 2026-10-02 22:01:04.296800

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2eddfa35bec"
down_revision: str | Sequence[str] | None = "5c2126ce0487"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_official_days",
        sa.Column("day_on", sa.Date(), nullable=False),
        sa.Column("is_workday", sa.Boolean(), nullable=False),
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('ntpc', 'dgpa')", name=op.f("ck_calendar_official_days_source")
        ),
        sa.CheckConstraint(
            "char_length(name) <= 100", name=op.f("ck_calendar_official_days_name_length")
        ),
        sa.PrimaryKeyConstraint("day_on", name=op.f("pk_calendar_official_days")),
    )
    op.create_table(
        "calendar_official_years",
        sa.Column("calendar_year", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('ntpc', 'dgpa')", name=op.f("ck_calendar_official_years_source")
        ),
        sa.CheckConstraint(
            "calendar_year BETWEEN 2000 AND 2200",
            name=op.f("ck_calendar_official_years_calendar_year_range"),
        ),
        sa.PrimaryKeyConstraint("calendar_year", name=op.f("pk_calendar_official_years")),
    )
    op.create_table(
        "calendar_overrides",
        sa.Column("day_on", sa.Date(), nullable=False),
        sa.Column("is_workday", sa.Boolean(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 100", name=op.f("ck_calendar_overrides_name_length")
        ),
        sa.CheckConstraint(
            "char_length(note) <= 500", name=op.f("ck_calendar_overrides_note_length")
        ),
        sa.PrimaryKeyConstraint("day_on", name=op.f("pk_calendar_overrides")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_overrides")
    op.drop_table("calendar_official_years")
    op.drop_table("calendar_official_days")
    # ### end Alembic commands ###
