"""建立核心資料表（含軟刪除欄位）

建立成員、專案、分類、任務、相依、Issue、留言、附件、刪除批次等資料表。

autogenerate 產生後手改兩處（其餘照產生的內容，逐行看過）：
- deletions.project_id 的外鍵：deletions 與 projects 互相參照，先建 deletions（不含這個外鍵）、
  再建 projects，最後補上這個外鍵。autogenerate 把它（use_alter=True）寫在 create_table 裡，
  但 CREATE TABLE 會略過 use_alter 的外鍵，不手改就少一個外鍵。
- downgrade：刪 projects 之前先拿掉這個外鍵，否則 DROP TABLE projects 會被擋。

各表的 deletion_id 外鍵是 DEFERRABLE INITIALLY DEFERRED（交易 commit 時才檢查），
跟 app/core/soft_delete.py 一致：清除回收桶或刪整個專案時，多層連動刪除不必依賴刪除順序。

Revision ID: 5c2126ce0487
Revises:
Create Date: 2026-10-02 16:28:31.148240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c2126ce0487"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_no", sa.Text(), nullable=True),
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("department", sa.Text(), server_default="", nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=False),
        sa.Column("can_login", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account ~ '^[a-z0-9._-]{1,64}$'", name=op.f("ck_members_account_format")
        ),
        sa.CheckConstraint("color ~ '^#[0-9a-f]{6}$'", name=op.f("ck_members_color_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("account", name=op.f("uq_members_account")),
    )
    op.create_index(
        "uq_members_employee_no",
        "members",
        ["employee_no"],
        unique=True,
        postgresql_where=sa.text("employee_no IS NOT NULL"),
    )
    op.create_table(
        "deletions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("root_kind", sa.Text(), nullable=False),
        sa.Column("root_id", sa.Uuid(), nullable=False),
        sa.Column("root_label", sa.Text(), nullable=False),
        sa.Column("deleted_by", sa.Uuid(), nullable=False),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "root_kind IN ('project', 'group', 'task', 'issue', 'comment')",
            name=op.f("ck_deletions_root_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"], ["members.id"], name=op.f("fk_deletions_deleted_by_members")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["deletions.id"],
            name=op.f("fk_deletions_parent_id_deletions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletions")),
    )
    op.create_index(op.f("ix_deletions_deleted_at"), "deletions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_deletions_parent_id"), "deletions", ["parent_id"], unique=False)
    op.create_index(
        "ix_deletions_project_id_deleted_at",
        "deletions",
        ["project_id", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("pm_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)",
            name=op.f("ck_projects_soft_delete_pair"),
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 100", name=op.f("ck_projects_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["members.id"], name=op.f("fk_projects_created_by_members")
        ),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_projects_deletion_id_deletions"),
        ),
        sa.ForeignKeyConstraint(["pm_id"], ["members.id"], name=op.f("fk_projects_pm_id_members")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_deletion_id"),
        "projects",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.create_index(
        "uq_projects_name_live",
        "projects",
        ["name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # projects 建好了，補上 deletions 指向 projects 的外鍵（見檔頭說明）。
    op.create_foreign_key(
        op.f("fk_deletions_project_id_projects"),
        "deletions",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "task_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)",
            name=op.f("ck_task_groups_soft_delete_pair"),
        ),
        sa.CheckConstraint("char_length(name) <= 200", name=op.f("ck_task_groups_name_length")),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_task_groups_deletion_id_deletions"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_task_groups_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_groups")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_task_groups_id")),
    )
    op.create_index(
        op.f("ix_task_groups_deletion_id"),
        "task_groups",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.create_index(
        "ix_task_groups_project_id_live",
        "task_groups",
        ["project_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_on", sa.Date(), nullable=False),
        sa.Column("start_on", sa.Date(), nullable=True),
        sa.Column("end_on", sa.Date(), nullable=True),
        sa.Column("done_on", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("priority IN ('high', 'mid', 'low')", name=op.f("ck_tasks_priority")),
        sa.CheckConstraint(
            "status IN ('todo', 'doing', 'paused', 'done')", name=op.f("ck_tasks_status")
        ),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)", name=op.f("ck_tasks_soft_delete_pair")
        ),
        sa.CheckConstraint("char_length(name) <= 200", name=op.f("ck_tasks_name_length")),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_tasks_deletion_id_deletions"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id", "project_id"],
            ["task_groups.id", "task_groups.project_id"],
            name=op.f("fk_tasks_group_id_task_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_tasks_id")),
    )
    op.create_index(
        op.f("ix_tasks_deletion_id"),
        "tasks",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_tasks_group_id"), "tasks", ["group_id"], unique=False)
    op.create_index(
        "ix_tasks_project_id_live",
        "tasks",
        ["project_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("created_on", sa.Date(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("item", sa.Text(), nullable=False),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("done_on", sa.Date(), nullable=True),
        sa.Column("ptype", sa.Text(), server_default="", nullable=False),
        sa.Column("pcb", sa.Text(), server_default="", nullable=False),
        sa.Column("bios", sa.Text(), server_default="", nullable=False),
        sa.Column("os", sa.Text(), server_default="", nullable=False),
        sa.Column("solved_bios", sa.Text(), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("solution", sa.Text(), server_default="", nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("item IN ('C', 'R', 'F', 'O')", name=op.f("ck_issues_item")),
        sa.CheckConstraint("level IN ('A', 'B', 'C', 'D')", name=op.f("ck_issues_level")),
        sa.CheckConstraint(
            "status IN ('open', 'doing', 'paused', 'closed')", name=op.f("ck_issues_status")
        ),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)", name=op.f("ck_issues_soft_delete_pair")
        ),
        sa.CheckConstraint("char_length(bios) <= 200", name=op.f("ck_issues_bios_length")),
        sa.CheckConstraint(
            "char_length(description) <= 20000", name=op.f("ck_issues_description_length")
        ),
        sa.CheckConstraint("char_length(os) <= 200", name=op.f("ck_issues_os_length")),
        sa.CheckConstraint("char_length(pcb) <= 200", name=op.f("ck_issues_pcb_length")),
        sa.CheckConstraint("char_length(ptype) <= 200", name=op.f("ck_issues_ptype_length")),
        sa.CheckConstraint(
            "char_length(solution) <= 20000", name=op.f("ck_issues_solution_length")
        ),
        sa.CheckConstraint(
            "char_length(solved_bios) <= 200", name=op.f("ck_issues_solved_bios_length")
        ),
        sa.CheckConstraint("char_length(title) <= 200", name=op.f("ck_issues_title_length")),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["members.id"], name=op.f("fk_issues_creator_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_issues_deletion_id_deletions"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "project_id"],
            ["tasks.id", "tasks.project_id"],
            name=op.f("fk_issues_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issues")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_issues_id")),
    )
    op.create_index(
        op.f("ix_issues_deletion_id"),
        "issues",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.create_table(
        "task_assignees",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_task_assignees_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_assignees_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", "member_id", name=op.f("pk_task_assignees")),
    )
    op.create_table(
        "task_deps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("from_task_id", sa.Uuid(), nullable=False),
        sa.Column("to_task_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)",
            name=op.f("ck_task_deps_soft_delete_pair"),
        ),
        sa.CheckConstraint("from_task_id <> to_task_id", name=op.f("ck_task_deps_not_self")),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_task_deps_deletion_id_deletions"),
        ),
        sa.ForeignKeyConstraint(
            ["from_task_id", "project_id"],
            ["tasks.id", "tasks.project_id"],
            name=op.f("fk_task_deps_from_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_task_id", "project_id"],
            ["tasks.id", "tasks.project_id"],
            name=op.f("fk_task_deps_to_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_deps")),
    )
    op.create_index(
        op.f("ix_task_deps_deletion_id"),
        "task_deps",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.create_index(
        "uq_task_deps_from_to_live",
        "task_deps",
        ["from_task_id", "to_task_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("target_kind", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("issue_id", sa.Uuid(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column(
            "posted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(target_kind = 'task' AND task_id IS NOT NULL AND issue_id IS NULL) OR (target_kind = 'issue' AND issue_id IS NOT NULL AND task_id IS NULL)",
            name=op.f("ck_comments_target"),
        ),
        sa.CheckConstraint(
            "target_kind IN ('task', 'issue')", name=op.f("ck_comments_target_kind")
        ),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)",
            name=op.f("ck_comments_soft_delete_pair"),
        ),
        sa.CheckConstraint("char_length(body) <= 10000", name=op.f("ck_comments_body_length")),
        sa.ForeignKeyConstraint(
            ["author_id"], ["members.id"], name=op.f("fk_comments_author_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_comments_deletion_id_deletions"),
        ),
        sa.ForeignKeyConstraint(
            ["issue_id", "project_id"],
            ["issues.id", "issues.project_id"],
            name=op.f("fk_comments_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "project_id"],
            ["tasks.id", "tasks.project_id"],
            name=op.f("fk_comments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(
        op.f("ix_comments_deletion_id"),
        "comments",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.create_table(
        "issue_owners",
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
            name=op.f("fk_issue_owners_issue_id_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f("fk_issue_owners_member_id_members"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("issue_id", "member_id", name=op.f("pk_issue_owners")),
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("stored_name", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(deleted_at IS NULL) = (deletion_id IS NULL)",
            name=op.f("ck_attachments_soft_delete_pair"),
        ),
        sa.CheckConstraint(
            "char_length(original_name) <= 255", name=op.f("ck_attachments_original_name_length")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_attachments_size_positive")),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_attachments_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["deletion_id"],
            ["deletions.id"],
            deferrable=True,
            initially="DEFERRED",
            name=op.f("fk_attachments_deletion_id_deletions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("stored_name", name=op.f("uq_attachments_stored_name")),
    )
    op.create_index(
        op.f("ix_attachments_deletion_id"),
        "attachments",
        ["deletion_id"],
        unique=False,
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_attachments_deletion_id"),
        table_name="attachments",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("attachments")
    op.drop_table("issue_owners")
    op.drop_index(
        op.f("ix_comments_deletion_id"),
        table_name="comments",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("comments")
    op.drop_index(
        "uq_task_deps_from_to_live",
        table_name="task_deps",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_task_deps_deletion_id"),
        table_name="task_deps",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("task_deps")
    op.drop_table("task_assignees")
    op.drop_index(
        op.f("ix_issues_deletion_id"),
        table_name="issues",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("issues")
    op.drop_index(
        "ix_tasks_project_id_live",
        table_name="tasks",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_tasks_group_id"), table_name="tasks")
    op.drop_index(
        op.f("ix_tasks_deletion_id"),
        table_name="tasks",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("tasks")
    op.drop_index(
        "ix_task_groups_project_id_live",
        table_name="task_groups",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_task_groups_deletion_id"),
        table_name="task_groups",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("task_groups")
    op.drop_constraint(op.f("fk_deletions_project_id_projects"), "deletions", type_="foreignkey")
    op.drop_index(
        "uq_projects_name_live",
        table_name="projects",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_projects_deletion_id"),
        table_name="projects",
        postgresql_where=sa.text("deletion_id IS NOT NULL"),
    )
    op.drop_table("projects")
    op.drop_index("ix_deletions_project_id_deleted_at", table_name="deletions")
    op.drop_index(op.f("ix_deletions_parent_id"), table_name="deletions")
    op.drop_index(op.f("ix_deletions_deleted_at"), table_name="deletions")
    op.drop_table("deletions")
    op.drop_index(
        "uq_members_employee_no",
        table_name="members",
        postgresql_where=sa.text("employee_no IS NOT NULL"),
    )
    op.drop_table("members")
    # ### end Alembic commands ###
