/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Calendar
         * @description 週末規則、官方資料完整涵蓋的年份，以及區間內跟預設規則不同或有名稱的日子。
         *
         *     `from`、`to` 都可以不給；`from` 晚於 `to`、日期格式錯、多餘的參數回 422。
         */
        get: operations["read_calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CalendarDay
         * @description 跟預設規則不同、或有名稱的一天。
         */
        CalendarDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Isworkday */
            isWorkday: boolean;
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "official" | "override";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkCalendar
         * @description 工作日曆。
         *
         *     前端算工作天：週六日照 `weekend_days`（ISO 8601 星期，1 = 週一 … 7 = 週日）放假、其他上班，
         *     `days` 裡有的照它；不在 `covered_years` 的年份只套週末規則，畫面要提示「假日資料未公布」。
         *     `days` 依日期遞增、同一天只有一筆；`covered_years` 遞增，代表那幾年官方日曆已完整匯入。
         */
        WorkCalendar: {
            /** Coveredyears */
            coveredYears: number[];
            /** Days */
            days: components["schemas"]["CalendarDay"][];
            /** Weekenddays */
            weekendDays: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_calendar_api_calendar_get: {
        parameters: {
            query?: {
                /** @description 區間起日（含），YYYY-MM-DD；不給就不設限 */
                from?: string | null;
                /** @description 區間迄日（含），YYYY-MM-DD；不給就不設限 */
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkCalendar"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
